# Generated by Django 2.2.3 on 2019-07-23 08:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.TextField(max_length=100)),
                ('context', models.TextField(max_length=255)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 23, 8, 18, 4, 943039, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('comment_con', models.TextField(max_length=255)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2019, 7, 23, 8, 18, 4, 943367, tzinfo=utc))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Post')),
            ],
        ),
    ]
